### ISSUE TITLE
CArray cannot exposed well to C with cbindgen

### ISSUE THREAD

**Issue by curiousmindflow** [snipsco/snips-utils-rs#42]
Hello,

First, is will explain my global application purpose:
I'm generating Rust struct and Rust struct repr(C) from IDL files. I've crated the parser (with Pest) and the dumper (with Tera).
The structures i generate are using this crate.
I need the users to be able to crate their IDLs, and do nothing else than compile to genereate new FFI header and .so where all the structures repr(C) i generated are exposed with cbindgen.

Sad point however, the complex types like CArray<T> are not exposed correctly, it's exposed like:
```rust
typedef struct MyStructure_t {
  unsigned char var1;
  const struct Type1_t *var2;
  const CArray<unsigned char> *var3;
  const CArray<short> *var4;
  const CArray<unsigned char> *var5;
  const CArray<short> *var6;
} MyStructure_t;
```
IDL:
```idl
#include "Type1.idl";

struct MyStructure {
    @key octet var1;
    Type1 var2;
    octet var3[9];
    short var4[9];
    sequence<octet> var5;
    sequence<short> var6;
};

```
File generated from previous IDL:
```rust
use std::ffi::*;
use ffi_convert::{AsRust, AsRustError, CArray, CDrop, CReprOf, CReprOfError, RawBorrow, RawPointerConverter};
use serde::{Deserialize, Serialize};
use rustdds::Keyed;

use super::{Type1::Type1,Type1_t};
#[derive(Debug, Serialize, Deserialize)]
pub struct MyStructure {
    var1: u8,
    var2: Type1,
    var3: Vec<u8>,
    var4: Vec<i16>,
    var5: Vec<u8>,
    var6: Vec<i16>,
}

impl MyStructure {
    pub fn to_c(self) -> Result<MyStructure_t, CReprOfError> {
        let c = MyStructure_t::c_repr_of(self);
        c
    }
}


impl Keyed for MyStructure {
    type K = u8;

    fn key(&self) -> Self::K {
        self.var1
    }
}
#[allow(non_camel_case_types)]
#[derive(Debug, CReprOf, AsRust, CDrop, RawPointerConverter)]
#[repr(C)]
#[target_type(MyStructure)]
pub struct MyStructure_t {
    var1: c_uchar,
    var2: *const Type1_t,
    var3: *const CArray<c_uchar>,
    var4: *const CArray<c_short>,
    var5: *const CArray<c_uchar>,
    var6: *const CArray<c_short>,
}

impl MyStructure_t {
    pub fn to_rust(&self) -> Result<MyStructure, AsRustError> {
        let pure = self.as_rust();
        pure
    }
}

```
How did you do to expose those kind of complex type to C through cbindgen please ?

**Comment by curiousmindflow** [comment]
Okay, i found the way.

I just didn't study enough cbindgen.
By default cbindgen don't expose types in dependencies and so in my case the CArray<T> type, which is part of ffi-convert and so a dependency, wasn't process at all.

Solution:
I use now the cbindgen.toml in which i set up few variables:
```toml
# https://github.com/eqrion/cbindgen/blob/master/docs.md

language = "C"
include_guard = "my_guard"
sys_includes = ["stdio.h", "string.h"]
cpp_compat = true
documentation = true

[export]
include = [
"MyStructure_t",
"MyEnumeration_t",
"Type2_t",
"Type1_t",

]
item_types = ["enums", "structs", "opaque", "functions"]

[parse]
parse_deps = true
include = ["ffi-convert"]

```
